### ISSUE TITLE
[CSS]: Öka storleken för emoji

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#100]
Just nu sätter WP storleken till 1em (ca: 14x14px) vilket blir väldigt litet.

``` css
img.wp-smiley, img.emoji {
  display: inline !important;
  border: none !important;
  box-shadow: none !important;
  height: 1em !important;
  width: 1em !important;
  margin: 0 .07em !important;
  vertical-align: -0.1em !important;
  background: none !important;
  padding: 0 !important;
}
```
