### ISSUE TITLE
[CSS]: Fix för bilder i delningsknappar

### ISSUE THREAD

**Issue by EyesX** [wpsvse/wpsv.se-archived#105]
När man lägger till anpassade delningsknappar så använder man bilder. Dessa blir inte alignade korrekt och behöver en liten fix. Gör regel generell för bilder i delningsknappar.

![pusha_share](https://cloud.githubusercontent.com/assets/4299787/7941570/7b1444de-0958-11e5-96f2-74fb1a1de628.png)

**Comment by marcustisater** [comment]
Nu ska det vara bra. Kan du dubbelkolla? Öppna om det skulle vara buggigt.

**Comment by EyesX** [comment]
Har du verkligen commitat denna ändring?

**Comment by EyesX** [comment]
``` css
.sd-social-icon .sd-content ul li[class*='share-'] a.sd-button.share-custom {
  padding: 8px 8px 6px 8px;
  top: 5px;
}
```

behöver bli

``` css
.sd-social-icon .sd-content ul li[class*='share-'] a.sd-button.share-custom {
  padding: 10px 8px 6px 8px;
  top: 5px;
}
```

Vi behöver också följande

``` css
.sd-social-icon .sd-content ul li[class*='share-'] a.sd-button.share-custom span {
    vertical-align: top;
}
```
